/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TradeDirection = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TradeImage = IDL.Record({
  'file' : ExternalBlob,
  'description' : IDL.Text,
});
export const ChecklistItemId = IDL.Text;
export const TradeChecklistItem = IDL.Record({
  'id' : ChecklistItemId,
  'description' : IDL.Text,
  'confirmed' : IDL.Bool,
});
export const TradeChecklist = IDL.Record({
  'items' : IDL.Vec(TradeChecklistItem),
});
export const AddTradeRequest = IDL.Record({
  'direction' : TradeDirection,
  'asset' : IDL.Text,
  'date' : Time,
  'takeProfit' : IDL.Float64,
  'tags' : IDL.Vec(IDL.Text),
  'positionSize' : IDL.Float64,
  'afterTradeImage' : IDL.Opt(TradeImage),
  'stopLoss' : IDL.Float64,
  'beforeTradeImage' : IDL.Opt(TradeImage),
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'checklist' : TradeChecklist,
  'exitPrice' : IDL.Float64,
});
export const TradeEntryId = IDL.Text;
export const TradeEntry = IDL.Record({
  'id' : TradeEntryId,
  'direction' : TradeDirection,
  'asset' : IDL.Text,
  'date' : Time,
  'takeProfit' : IDL.Float64,
  'tags' : IDL.Vec(IDL.Text),
  'profitLoss' : IDL.Float64,
  'positionSize' : IDL.Float64,
  'riskPercentage' : IDL.Float64,
  'afterTradeImage' : IDL.Opt(TradeImage),
  'stopLoss' : IDL.Float64,
  'beforeTradeImage' : IDL.Opt(TradeImage),
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'checklist' : TradeChecklist,
  'exitPrice' : IDL.Float64,
  'riskRewardRatio' : IDL.Float64,
});
export const GoalStatus = IDL.Variant({
  'atLimit' : IDL.Null,
  'overTarget' : IDL.Null,
  'onTrack' : IDL.Null,
  'underTarget' : IDL.Null,
});
export const AchievementBadgeStatus = IDL.Variant({
  'goalAchieved' : IDL.Null,
  'targetReached' : IDL.Null,
  'milestone' : IDL.Null,
});
export const AchievementBadge = IDL.Record({
  'status' : AchievementBadgeStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const PerformanceGoalsSummary = IDL.Record({
  'weeklyProgress' : IDL.Float64,
  'maxDrawdownLimit' : IDL.Float64,
  'weeklyGoalStatus' : GoalStatus,
  'currentDrawdown' : IDL.Float64,
  'goalStatus' : GoalStatus,
  'monthlyProfitProgress' : IDL.Float64,
  'currentWeekProfit' : IDL.Float64,
  'weeklyProfitTarget' : IDL.Float64,
  'monthlyProfitGoal' : IDL.Float64,
  'achievementBadge' : IDL.Opt(AchievementBadge),
});
export const AddTradeResult = IDL.Record({
  'trade' : TradeEntry,
  'updatedGoals' : PerformanceGoalsSummary,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PerformanceGoals = IDL.Record({
  'maxDrawdownLimit' : IDL.Float64,
  'weeklyProfitTarget' : IDL.Float64,
  'monthlyProfitGoal' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'performanceGoals' : PerformanceGoals,
  'accountBalance' : IDL.Float64,
  'currency' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTradeEntry' : IDL.Func([AddTradeRequest], [AddTradeResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTradeEntry' : IDL.Func([TradeEntryId], [PerformanceGoalsSummary], []),
  'getAllTradeEntries' : IDL.Func([], [IDL.Vec(TradeEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaginatedTrades' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(TradeEntry)],
      ['query'],
    ),
  'getPerformanceGoalsSummary' : IDL.Func(
      [],
      [PerformanceGoalsSummary],
      ['query'],
    ),
  'getTradeById' : IDL.Func([TradeEntryId], [IDL.Opt(TradeEntry)], ['query']),
  'getTradeStatistics' : IDL.Func(
      [],
      [IDL.Record({ 'totalTrades' : IDL.Nat, 'totalProfit' : IDL.Float64 })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TradeDirection = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TradeImage = IDL.Record({
    'file' : ExternalBlob,
    'description' : IDL.Text,
  });
  const ChecklistItemId = IDL.Text;
  const TradeChecklistItem = IDL.Record({
    'id' : ChecklistItemId,
    'description' : IDL.Text,
    'confirmed' : IDL.Bool,
  });
  const TradeChecklist = IDL.Record({ 'items' : IDL.Vec(TradeChecklistItem) });
  const AddTradeRequest = IDL.Record({
    'direction' : TradeDirection,
    'asset' : IDL.Text,
    'date' : Time,
    'takeProfit' : IDL.Float64,
    'tags' : IDL.Vec(IDL.Text),
    'positionSize' : IDL.Float64,
    'afterTradeImage' : IDL.Opt(TradeImage),
    'stopLoss' : IDL.Float64,
    'beforeTradeImage' : IDL.Opt(TradeImage),
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'checklist' : TradeChecklist,
    'exitPrice' : IDL.Float64,
  });
  const TradeEntryId = IDL.Text;
  const TradeEntry = IDL.Record({
    'id' : TradeEntryId,
    'direction' : TradeDirection,
    'asset' : IDL.Text,
    'date' : Time,
    'takeProfit' : IDL.Float64,
    'tags' : IDL.Vec(IDL.Text),
    'profitLoss' : IDL.Float64,
    'positionSize' : IDL.Float64,
    'riskPercentage' : IDL.Float64,
    'afterTradeImage' : IDL.Opt(TradeImage),
    'stopLoss' : IDL.Float64,
    'beforeTradeImage' : IDL.Opt(TradeImage),
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'checklist' : TradeChecklist,
    'exitPrice' : IDL.Float64,
    'riskRewardRatio' : IDL.Float64,
  });
  const GoalStatus = IDL.Variant({
    'atLimit' : IDL.Null,
    'overTarget' : IDL.Null,
    'onTrack' : IDL.Null,
    'underTarget' : IDL.Null,
  });
  const AchievementBadgeStatus = IDL.Variant({
    'goalAchieved' : IDL.Null,
    'targetReached' : IDL.Null,
    'milestone' : IDL.Null,
  });
  const AchievementBadge = IDL.Record({
    'status' : AchievementBadgeStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const PerformanceGoalsSummary = IDL.Record({
    'weeklyProgress' : IDL.Float64,
    'maxDrawdownLimit' : IDL.Float64,
    'weeklyGoalStatus' : GoalStatus,
    'currentDrawdown' : IDL.Float64,
    'goalStatus' : GoalStatus,
    'monthlyProfitProgress' : IDL.Float64,
    'currentWeekProfit' : IDL.Float64,
    'weeklyProfitTarget' : IDL.Float64,
    'monthlyProfitGoal' : IDL.Float64,
    'achievementBadge' : IDL.Opt(AchievementBadge),
  });
  const AddTradeResult = IDL.Record({
    'trade' : TradeEntry,
    'updatedGoals' : PerformanceGoalsSummary,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PerformanceGoals = IDL.Record({
    'maxDrawdownLimit' : IDL.Float64,
    'weeklyProfitTarget' : IDL.Float64,
    'monthlyProfitGoal' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'performanceGoals' : PerformanceGoals,
    'accountBalance' : IDL.Float64,
    'currency' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTradeEntry' : IDL.Func([AddTradeRequest], [AddTradeResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTradeEntry' : IDL.Func(
        [TradeEntryId],
        [PerformanceGoalsSummary],
        [],
      ),
    'getAllTradeEntries' : IDL.Func([], [IDL.Vec(TradeEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaginatedTrades' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(TradeEntry)],
        ['query'],
      ),
    'getPerformanceGoalsSummary' : IDL.Func(
        [],
        [PerformanceGoalsSummary],
        ['query'],
      ),
    'getTradeById' : IDL.Func([TradeEntryId], [IDL.Opt(TradeEntry)], ['query']),
    'getTradeStatistics' : IDL.Func(
        [],
        [IDL.Record({ 'totalTrades' : IDL.Nat, 'totalProfit' : IDL.Float64 })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };