/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AchievementBadge {
  'status' : AchievementBadgeStatus,
  'title' : string,
  'description' : string,
  'timestamp' : Time,
}
export type AchievementBadgeStatus = { 'goalAchieved' : null } |
  { 'targetReached' : null } |
  { 'milestone' : null };
export interface AddTradeRequest {
  'direction' : TradeDirection,
  'asset' : string,
  'date' : Time,
  'takeProfit' : number,
  'tags' : Array<string>,
  'positionSize' : number,
  'afterTradeImage' : [] | [TradeImage],
  'stopLoss' : number,
  'beforeTradeImage' : [] | [TradeImage],
  'notes' : string,
  'entryPrice' : number,
  'checklist' : TradeChecklist,
  'exitPrice' : number,
}
export interface AddTradeResult {
  'trade' : TradeEntry,
  'updatedGoals' : PerformanceGoalsSummary,
}
export type ChecklistItemId = string;
export type ExternalBlob = Uint8Array;
export type GoalStatus = { 'atLimit' : null } |
  { 'overTarget' : null } |
  { 'onTrack' : null } |
  { 'underTarget' : null };
export interface PerformanceGoals {
  'maxDrawdownLimit' : number,
  'weeklyProfitTarget' : number,
  'monthlyProfitGoal' : number,
}
export interface PerformanceGoalsSummary {
  'weeklyProgress' : number,
  'maxDrawdownLimit' : number,
  'weeklyGoalStatus' : GoalStatus,
  'currentDrawdown' : number,
  'goalStatus' : GoalStatus,
  'monthlyProfitProgress' : number,
  'currentWeekProfit' : number,
  'weeklyProfitTarget' : number,
  'monthlyProfitGoal' : number,
  'achievementBadge' : [] | [AchievementBadge],
}
export type Time = bigint;
export interface TradeChecklist { 'items' : Array<TradeChecklistItem> }
export interface TradeChecklistItem {
  'id' : ChecklistItemId,
  'description' : string,
  'confirmed' : boolean,
}
export type TradeDirection = { 'buy' : null } |
  { 'sell' : null };
export interface TradeEntry {
  'id' : TradeEntryId,
  'direction' : TradeDirection,
  'asset' : string,
  'date' : Time,
  'takeProfit' : number,
  'tags' : Array<string>,
  'profitLoss' : number,
  'positionSize' : number,
  'riskPercentage' : number,
  'afterTradeImage' : [] | [TradeImage],
  'stopLoss' : number,
  'beforeTradeImage' : [] | [TradeImage],
  'notes' : string,
  'entryPrice' : number,
  'checklist' : TradeChecklist,
  'exitPrice' : number,
  'riskRewardRatio' : number,
}
export type TradeEntryId = string;
export interface TradeImage { 'file' : ExternalBlob, 'description' : string }
export interface UserProfile {
  'name' : string,
  'performanceGoals' : PerformanceGoals,
  'accountBalance' : number,
  'currency' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTradeEntry' : ActorMethod<[AddTradeRequest], AddTradeResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTradeEntry' : ActorMethod<[TradeEntryId], PerformanceGoalsSummary>,
  'getAllTradeEntries' : ActorMethod<[], Array<TradeEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaginatedTrades' : ActorMethod<[bigint, bigint], Array<TradeEntry>>,
  'getPerformanceGoalsSummary' : ActorMethod<[], PerformanceGoalsSummary>,
  'getTradeById' : ActorMethod<[TradeEntryId], [] | [TradeEntry]>,
  'getTradeStatistics' : ActorMethod<
    [],
    { 'totalTrades' : bigint, 'totalProfit' : number }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];