/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TradeImage {
    file: ExternalBlob;
    description: string;
}
export interface AddTradeRequest {
    direction: TradeDirection;
    asset: string;
    date: Time;
    takeProfit: number;
    tags: Array<string>;
    positionSize: number;
    afterTradeImage?: TradeImage;
    stopLoss: number;
    beforeTradeImage?: TradeImage;
    notes: string;
    entryPrice: number;
    checklist: TradeChecklist;
    exitPrice: number;
}
export type Time = bigint;
export interface PerformanceGoals {
    maxDrawdownLimit: number;
    weeklyProfitTarget: number;
    monthlyProfitGoal: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TradeChecklist {
    items: Array<TradeChecklistItem>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PerformanceGoalsSummary {
    weeklyProgress: number;
    maxDrawdownLimit: number;
    weeklyGoalStatus: GoalStatus;
    currentDrawdown: number;
    goalStatus: GoalStatus;
    monthlyProfitProgress: number;
    currentWeekProfit: number;
    weeklyProfitTarget: number;
    monthlyProfitGoal: number;
    achievementBadge?: AchievementBadge;
}
export type ChecklistItemId = string;
export interface TradeChecklistItem {
    id: ChecklistItemId;
    description: string;
    confirmed: boolean;
}
export interface AddTradeResult {
    trade: TradeEntry;
    updatedGoals: PerformanceGoalsSummary;
}
export interface AchievementBadge {
    status: AchievementBadgeStatus;
    title: string;
    description: string;
    timestamp: Time;
}
export interface TradeEntry {
    id: TradeEntryId;
    direction: TradeDirection;
    asset: string;
    date: Time;
    takeProfit: number;
    tags: Array<string>;
    profitLoss: number;
    positionSize: number;
    riskPercentage: number;
    afterTradeImage?: TradeImage;
    stopLoss: number;
    beforeTradeImage?: TradeImage;
    notes: string;
    entryPrice: number;
    checklist: TradeChecklist;
    exitPrice: number;
    riskRewardRatio: number;
}
export type TradeEntryId = string;
export interface UserProfile {
    name: string;
    performanceGoals: PerformanceGoals;
    accountBalance: number;
    currency: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AchievementBadgeStatus {
    goalAchieved = "goalAchieved",
    targetReached = "targetReached",
    milestone = "milestone"
}
export enum GoalStatus {
    atLimit = "atLimit",
    overTarget = "overTarget",
    onTrack = "onTrack",
    underTarget = "underTarget"
}
export enum TradeDirection {
    buy = "buy",
    sell = "sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTradeEntry(request: AddTradeRequest): Promise<AddTradeResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteTradeEntry(tradeId: TradeEntryId): Promise<PerformanceGoalsSummary>;
    getAllTradeEntries(): Promise<Array<TradeEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPaginatedTrades(page: bigint, pageSize: bigint): Promise<Array<TradeEntry>>;
    getPerformanceGoalsSummary(): Promise<PerformanceGoalsSummary>;
    getTradeById(tradeId: TradeEntryId): Promise<TradeEntry | null>;
    getTradeStatistics(): Promise<{
        totalTrades: bigint;
        totalProfit: number;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { AchievementBadge as _AchievementBadge, AchievementBadgeStatus as _AchievementBadgeStatus, AddTradeRequest as _AddTradeRequest, AddTradeResult as _AddTradeResult, ExternalBlob as _ExternalBlob, GoalStatus as _GoalStatus, PerformanceGoalsSummary as _PerformanceGoalsSummary, Time as _Time, TradeChecklist as _TradeChecklist, TradeDirection as _TradeDirection, TradeEntry as _TradeEntry, TradeEntryId as _TradeEntryId, TradeImage as _TradeImage, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTradeEntry(arg0: AddTradeRequest): Promise<AddTradeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addTradeEntry(await to_candid_AddTradeRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AddTradeResult_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTradeEntry(await to_candid_AddTradeRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AddTradeResult_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteTradeEntry(arg0: TradeEntryId): Promise<PerformanceGoalsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTradeEntry(arg0);
                return from_candid_PerformanceGoalsSummary_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTradeEntry(arg0);
            return from_candid_PerformanceGoalsSummary_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTradeEntries(): Promise<Array<TradeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTradeEntries();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTradeEntries();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaginatedTrades(arg0: bigint, arg1: bigint): Promise<Array<TradeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaginatedTrades(arg0, arg1);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaginatedTrades(arg0, arg1);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceGoalsSummary(): Promise<PerformanceGoalsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceGoalsSummary();
                return from_candid_PerformanceGoalsSummary_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceGoalsSummary();
            return from_candid_PerformanceGoalsSummary_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeById(arg0: TradeEntryId): Promise<TradeEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeById(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeById(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeStatistics(): Promise<{
        totalTrades: bigint;
        totalProfit: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeStatistics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeStatistics();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_AchievementBadgeStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AchievementBadgeStatus): AchievementBadgeStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_AchievementBadge_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AchievementBadge): AchievementBadge {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_AddTradeResult_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddTradeResult): Promise<AddTradeResult> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GoalStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalStatus): GoalStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PerformanceGoalsSummary_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PerformanceGoalsSummary): PerformanceGoalsSummary {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TradeDirection_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeDirection): TradeDirection {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_TradeEntry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeEntry): Promise<TradeEntry> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_TradeImage_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeImage): Promise<TradeImage> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TradeImage]): Promise<TradeImage | null> {
    return value.length === 0 ? null : await from_candid_TradeImage_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AchievementBadge]): AchievementBadge | null {
    return value.length === 0 ? null : from_candid_AchievementBadge_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TradeEntry]): Promise<TradeEntry | null> {
    return value.length === 0 ? null : await from_candid_TradeEntry_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trade: _TradeEntry;
    updatedGoals: _PerformanceGoalsSummary;
}): Promise<{
    trade: TradeEntry;
    updatedGoals: PerformanceGoalsSummary;
}> {
    return {
        trade: await from_candid_TradeEntry_n17(_uploadFile, _downloadFile, value.trade),
        updatedGoals: from_candid_PerformanceGoalsSummary_n25(_uploadFile, _downloadFile, value.updatedGoals)
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TradeEntryId;
    direction: _TradeDirection;
    asset: string;
    date: _Time;
    takeProfit: number;
    tags: Array<string>;
    profitLoss: number;
    positionSize: number;
    riskPercentage: number;
    afterTradeImage: [] | [_TradeImage];
    stopLoss: number;
    beforeTradeImage: [] | [_TradeImage];
    notes: string;
    entryPrice: number;
    checklist: _TradeChecklist;
    exitPrice: number;
    riskRewardRatio: number;
}): Promise<{
    id: TradeEntryId;
    direction: TradeDirection;
    asset: string;
    date: Time;
    takeProfit: number;
    tags: Array<string>;
    profitLoss: number;
    positionSize: number;
    riskPercentage: number;
    afterTradeImage?: TradeImage;
    stopLoss: number;
    beforeTradeImage?: TradeImage;
    notes: string;
    entryPrice: number;
    checklist: TradeChecklist;
    exitPrice: number;
    riskRewardRatio: number;
}> {
    return {
        id: value.id,
        direction: from_candid_TradeDirection_n19(_uploadFile, _downloadFile, value.direction),
        asset: value.asset,
        date: value.date,
        takeProfit: value.takeProfit,
        tags: value.tags,
        profitLoss: value.profitLoss,
        positionSize: value.positionSize,
        riskPercentage: value.riskPercentage,
        afterTradeImage: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.afterTradeImage)),
        stopLoss: value.stopLoss,
        beforeTradeImage: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.beforeTradeImage)),
        notes: value.notes,
        entryPrice: value.entryPrice,
        checklist: value.checklist,
        exitPrice: value.exitPrice,
        riskRewardRatio: value.riskRewardRatio
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    file: _ExternalBlob;
    description: string;
}): Promise<{
    file: ExternalBlob;
    description: string;
}> {
    return {
        file: await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.file),
        description: value.description
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weeklyProgress: number;
    maxDrawdownLimit: number;
    weeklyGoalStatus: _GoalStatus;
    currentDrawdown: number;
    goalStatus: _GoalStatus;
    monthlyProfitProgress: number;
    currentWeekProfit: number;
    weeklyProfitTarget: number;
    monthlyProfitGoal: number;
    achievementBadge: [] | [_AchievementBadge];
}): {
    weeklyProgress: number;
    maxDrawdownLimit: number;
    weeklyGoalStatus: GoalStatus;
    currentDrawdown: number;
    goalStatus: GoalStatus;
    monthlyProfitProgress: number;
    currentWeekProfit: number;
    weeklyProfitTarget: number;
    monthlyProfitGoal: number;
    achievementBadge?: AchievementBadge;
} {
    return {
        weeklyProgress: value.weeklyProgress,
        maxDrawdownLimit: value.maxDrawdownLimit,
        weeklyGoalStatus: from_candid_GoalStatus_n27(_uploadFile, _downloadFile, value.weeklyGoalStatus),
        currentDrawdown: value.currentDrawdown,
        goalStatus: from_candid_GoalStatus_n27(_uploadFile, _downloadFile, value.goalStatus),
        monthlyProfitProgress: value.monthlyProfitProgress,
        currentWeekProfit: value.currentWeekProfit,
        weeklyProfitTarget: value.weeklyProfitTarget,
        monthlyProfitGoal: value.monthlyProfitGoal,
        achievementBadge: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.achievementBadge))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AchievementBadgeStatus;
    title: string;
    description: string;
    timestamp: _Time;
}): {
    status: AchievementBadgeStatus;
    title: string;
    description: string;
    timestamp: Time;
} {
    return {
        status: from_candid_AchievementBadgeStatus_n32(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeDirection {
    return "buy" in value ? TradeDirection.buy : "sell" in value ? TradeDirection.sell : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    atLimit: null;
} | {
    overTarget: null;
} | {
    onTrack: null;
} | {
    underTarget: null;
}): GoalStatus {
    return "atLimit" in value ? GoalStatus.atLimit : "overTarget" in value ? GoalStatus.overTarget : "onTrack" in value ? GoalStatus.onTrack : "underTarget" in value ? GoalStatus.underTarget : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalAchieved: null;
} | {
    targetReached: null;
} | {
    milestone: null;
}): AchievementBadgeStatus {
    return "goalAchieved" in value ? AchievementBadgeStatus.goalAchieved : "targetReached" in value ? AchievementBadgeStatus.targetReached : "milestone" in value ? AchievementBadgeStatus.milestone : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeEntry>): Promise<Array<TradeEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TradeEntry_n17(_uploadFile, _downloadFile, x)));
}
async function to_candid_AddTradeRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddTradeRequest): Promise<_AddTradeRequest> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_TradeDirection_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): _TradeDirection {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_TradeImage_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeImage): Promise<_TradeImage> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    file: ExternalBlob;
    description: string;
}): Promise<{
    file: _ExternalBlob;
    description: string;
}> {
    return {
        file: await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.file),
        description: value.description
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: TradeDirection;
    asset: string;
    date: Time;
    takeProfit: number;
    tags: Array<string>;
    positionSize: number;
    afterTradeImage?: TradeImage;
    stopLoss: number;
    beforeTradeImage?: TradeImage;
    notes: string;
    entryPrice: number;
    checklist: TradeChecklist;
    exitPrice: number;
}): Promise<{
    direction: _TradeDirection;
    asset: string;
    date: _Time;
    takeProfit: number;
    tags: Array<string>;
    positionSize: number;
    afterTradeImage: [] | [_TradeImage];
    stopLoss: number;
    beforeTradeImage: [] | [_TradeImage];
    notes: string;
    entryPrice: number;
    checklist: _TradeChecklist;
    exitPrice: number;
}> {
    return {
        direction: to_candid_TradeDirection_n10(_uploadFile, _downloadFile, value.direction),
        asset: value.asset,
        date: value.date,
        takeProfit: value.takeProfit,
        tags: value.tags,
        positionSize: value.positionSize,
        afterTradeImage: value.afterTradeImage ? candid_some(await to_candid_TradeImage_n12(_uploadFile, _downloadFile, value.afterTradeImage)) : candid_none(),
        stopLoss: value.stopLoss,
        beforeTradeImage: value.beforeTradeImage ? candid_some(await to_candid_TradeImage_n12(_uploadFile, _downloadFile, value.beforeTradeImage)) : candid_none(),
        notes: value.notes,
        entryPrice: value.entryPrice,
        checklist: value.checklist,
        exitPrice: value.exitPrice
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeDirection.buy ? {
        buy: null
    } : value == TradeDirection.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
